/*4.4 En base a las asignaciones vigentes, calcular la fecha en la que al menos la mitad de los usuarios activos ya no tienen trabajo asignado.
...*/

SELECT ASSIGNMENTS.END_DATE AS STIMATED_DATE
FROM ASSIGNMENTS
INNER JOIN USERS
ON USERS.ID=ASSIGNMENTS.USER_ID
WHERE END_DATE >= '2022-03-01' AND USERS.ENABLED = TRUE
ORDER BY END_DATE ASC
OFFSET (SELECT COUNT(ASSIGNMENTS.ID) FROM ASSIGNMENTS WHERE END_DATE >= '2022-03-01')*0.50
LIMIT 1;